### PR TITLE
#9 - add support for bitbucket issues

### PR DESCRIPTION
**Pull request by tshedor**
@edlefebvre could you please test this script out in the wild before I publish it to NPM? I made a few unit tests for it and those function as expected, but I'm concerned about the `updated` call, as the [Bitbucket docs on this field](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Updated) could be misleading. 

If it functions as expected in the wild, I'll merge this in.

### CODE REVIEW

**Comment by edlefebvre** [comment]
Hi tshedor, thanks for this work! It doesn't seem to work though, but maybe I did something wrong?

- I updated the webhook so that it triggers on issues.
- After placing the new files in node_modules/hubot-bitbucket-pr, the PR actions still work as expected, but nothing on issues.

Am I missing something?

**Comment by tshedor** [comment]
@edlefebvre Sorry about that - totally redefined the all-important `@type` instance variable on creation. You weren't missing anything in those install steps. Could you please give it one more whirl?

**Comment by edlefebvre** [comment]
@tshedor it works perfectly now! Thank you very much.

**Comment by tshedor** [comment]
Awesome. I'm going to bump the version and close everything out.

**Pull request merged**
