### PR TITLE
make sending attachments compatible with slack-adapter v4

### PR DESCRIPTION
**Pull request by madflow**
This script would not work for me when using the slack adapter 4.3.1. This PR documents what fixed it for me.

### CODE REVIEW

**Comment by tshedor** [comment]
@madflow Thanks for fixing this; I had once upgraded from the v3.x adapter to v4 and broke everything.

Would you please add a control statement checking the adapter version before using this payload? Because while this will allow attachments to exist again in v4, it will break attachments for anyone still using v3.

**Comment by madflow** [comment]
Do you have any idea how to get the adapter version?

**Comment by tshedor** [comment]
@madflow So I did a little bit digging. Turns out the version number is obscured between packages (to a degree, but definitely outside the realm of what we'd require) for security reasons.

Instead, I looked for inconsistencies between the v3 and v4 API.

v3:
```
{ SlackBot:
  { [Function: SlackBot]
    listenerCount: [Function],
    __super__:
     { constructor: [Object],
       send: [Function],
       emote: [Function],
       reply: [Function],
       topic: [Function],
       play: [Function],
       run: [Function],
       close: [Function],
       receive: [Function],
       users: [Function],
       userForId: [Function],
       userForName: [Function],
       usersForRawFuzzyName: [Function],
       usersForFuzzyName: [Function],
       http: [Function] },
    MAX_MESSAGE_LENGTH: 4000,
    MIN_MESSAGE_LENGTH: 1,
    RESERVED_KEYWORDS: [ 'channel', 'group', 'everyone', 'here' ] },
 SlackTextMessage:
  { [Function: SlackTextMessage]
    __super__:
     { constructor: [Object],
       match: [Function],
       toString: [Function] } },
 SlackRawMessage: { [Function: SlackRawMessage] __super__: { finish: [Function] } },
 SlackBotMessage: { [Function: SlackBotMessage] __super__: { constructor: [Object] } },
 SlackRawListener: { [Function: SlackRawListener] __super__: { call: [Function] } },
 SlackBotListener: { [Function: SlackBotListener] __super__: { call: [Function] } },
 use: [Function] }
 ```

v4
```
{ use: [Function] }
```

So I've tested this snippet, adding your work within a control statement: 

```coffeescript
    # Slack special formatting
    if robot.adapterName is 'slack'
      slack_adapter_obj = require('hubot-slack')
      event = new SlackPullRequestEvent(robot, resp, type)

      msg =
        message:
          reply_to: room
          room: room
        content: event.getMessage()

      # Slack adapter changed how attachments are handled in v4; this is an ugly hack that checks for the existence of a depreciated exposed property
      if slack_adapter_obj.SlackRawMessage?
        robot.emit 'slack-attachment', msg

      else
        payload =
          attachments: [msg.content]
        robot.send room: room, payload
```

What do you think? It's a bit hacky, but it's the best solution I've been able to produce.

**Comment by madflow** [comment]
It is a hack - but a creative one :D 

My first reaction was: Release Version 2.0 with this BC break and forget about the legacy slack adapter. But - since this script is not Slack specific and it is not pinned to a specific adapter version, it might be nicer to hack around it.

**Comment by tshedor** [comment]
Yeah, I'd rather hack around the versions and depreciate over a great discrepancy between versions (i.e. remove this hack after Hubot Slack reaches v5). 

In that case, would you mind updating your PR to include this new code? I'll merge after.

**Comment by tshedor** [comment]
Also, just checked out your profile and saw you're in Cologne. Cheers from Berlin.

**Comment by madflow** [comment]
Ahh - finally someone in the same timezone on Github :D 

I updated the PR and did a quick test with our "Hubot" in Slack. Looks like it is working fine!

**Comment by tshedor** [comment]
Sehr gut. Thanks, friend.

**Pull request merged**
